services:
  node:
    container_name: app
    build:
      context: node
    networks:
      - nodeapp
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: server
    build:
      context: nginx
    ports:
      - '8080:80'
    networks:
      - nodeapp
    depends_on:
      - node

  db:
    container_name: db
    image: mariadb:latest
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/mysql:Z
    environment:
      MARIADB_DATABASE: nodedb
      MARIADB_ROOT_PASSWORD: nodedb
    networks:
      - nodeapp
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  nodeapp:
    driver: bridge
