services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - '3000:3000'

  db:
    image: mysql:latest
    platform: linux/arm64
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: nodedb
    ports:
      - '3316:3306'
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
