services:
  db:
    image: mysql:latest
    platform: linux/arm64
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_USER: node
      MYSQL_ROOT_PASSWORD: nodedb

    networks:
      - node-network

networks:
  node-network:
    driver: bridge
