services:
  app:
    build:
      context: node
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    platform: linux/arm64
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: nodedb
    ports:
      - '3316:3306'
    networks:
      - node-network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  node-network:
    driver: bridge
